routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);
Auth::routes();


Route::get('/', 'Web\KrucukController@index')->name('index');
Route::get('/detail/{id}', 'Web\KrucukController@detail')->name('detail');
Route::get('/search', 'Web\KrucukController@search')->name('search');
Route::get('/category/{slug}', 'Web\KrucukController@category')->name('category');
Route::post('/rate', 'Web\KrucukController@rateMerchant')->name('rate');
Route::get('/login', 'Web\KrucukController@login')->name('login');
Route::get('/register', 'Web\KrucukController@register')->name('register');
Route::post('/register/create', 'Web\KrucukController@registerCreate');
Route::get('/login-merchant', 'Web\KrucukController@loginMerchant')->name('login-merchant');
Route::get('/register-merchant', 'Web\KrucukController@registerMerchant')->name('register-merchant');
Route::post('/register-merchant/create', 'Web\KrucukController@registerMerchantCreate')->name('register-merchant-create');

Route::prefix('merchant')
     ->namespace('Web')
     ->group(function(){
          Route::get('/setting','MerchantController@setting')->name('merchant-setting');
          Route::post('/setting-update','MerchantController@settingUpdate')->name('merchant-setting-update');
          Route::get('/operational','MerchantController@operational')->name('merchant-operational');
          Route::post('/operational-update','MerchantController@operationalUpdate')->name('merchant-operational-update');
          Route::get('/information','MerchantController@information')->name('merchant-information');
          Route::post('/information-update','MerchantController@informationUpdate')->name('merchant-information-update');
          Route::get('/gallery','MerchantController@gallery')->name('merchant-gallery');
          Route::post('/gallery-update','MerchantController@galleryUpdate')->name('merchant-gallery-update');
          Route::get('/gallery-delete/{id}','MerchantController@galleryDelete')->name('merchant-gallery-delete');
          Route::get('/menu','MerchantController@menu')->name('merchant-menu');
          Route::post('/menu-update','MerchantController@menuUpdate')->name('merchant-menu-update');
     });

Route::prefix('admin')
     ->namespace('Admin')
     ->group(function(){
          Route::get('/','Dashboard@index');
          Route::resource('category','CategoryController');
          Route::resource('admin','AdminController');
          Route::resource('user','UserController');
          Route::resource('merchant','MerchantController')->names([
               'update' => 'merchant.update',
          ]);
          Route::resource('banner','BannerController');
     });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\Admin\AdminRequest;
use App\Http\Controllers\Controller;
use App\user;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $data['contents'] = User::all()->where('role','user');
        return view('pages.admin.user.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRequest $request)
    {
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['item'] = Admin::findOrFail($id);
        return view('pages.admin.admin.form',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $data['form'] = 'edit';
        $data['item'] = User::findOrFail($id);
        return view('pages.admin.user.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data['status'] = $request->status;
        $db = User::where('id',$id);
        
        $db->update($data);
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Admin::findOrfail($id);
        $item->delete();

        return redirect()->route('admin.index');
    }
}

resources/views/pages/admin/user/form.blade.php
@extends('layouts.admin')

@section('title','Kategori Form')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>User Forms</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item">User</div>
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                         <form action="{{route('user.update',$item->id)}}" method="POST">
                            @php
                                if($form =='edit'){
                                    echo method_field('PUT');
                                }
                            @endphp
                            @csrf
                        <div class="card-body row">
                            <div class="form-group col-md-6 col-12">
                                <label>Nama</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{isset($item->name)?$item->name:old('name')}}" readonly>
                                @error('name')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label>Email</label>
                                <input type="email" name="email" id="email" class="form-control" value="{{isset($item->email)?$item->email:old('email')}}" readonly>
                                @error('email')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label>Phone</label>
                                <input type="phone" name="phone" id="phone" class="form-control" value="{{isset($item->phone)?$item->phone:old('phone')}}" readonly>
                                @error('phone')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label>Birth Date</label>
                                <input type="date" name="birth_date" id="birth_date" class="form-control" value="{{isset($item->birth_date)?$item->birth_date:old('birth_date')}}" readonly>
                                @error('birth_date')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label>Address</label>
                                <textarea name="address" id="" rows="10" class="form-control" readonly> {{isset($item->address)?$item->address:old('address')}}</textarea>
                                @error('address')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label class="d-block">Status</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="status" id="status1" value="1" {{isset($item->status)?($item->status == '1')?'checked="checked"':'':old('title')}}>
                                    <label class="form-check-label" for="status1">
                                        On
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="status" id="status2" value="0" {{isset($item->status)?($item->status == '0')?'checked="checked"':'':old('title')}}>
                                    <label class="form-check-label" for="status2">
                                        Off
                                    </label>
                                </div>
                                @error('status')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="card-footer text-right">
                                <button type="submit" class="btn btn-primary pull-right">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/pages/admin/user/index.blade.php
@extends('layouts.admin')

@section('title','Kategori')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>User</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item">User</div>
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>User List</h4>
                            <div class="card-header-form">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped table-md">
                                    <tbody>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                        @php
                                            $no = 1;
                                        @endphp
                                        @foreach ($contents as $content)
                                        <tr>
                                            <td>{{$no}}</td>
                                            <td>{{$content->name}}</td>
                                            <td>{{$content->email}}</td>
                                            <td>
                                                @if ($content->status == 1)
                                                    <div class="badge badge-success">Active</div>
                                                @else
                                                    <div class="badge badge-danger">Not Active</div>
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{route('user.edit',$content->id)}}" class="btn btn-info"><i class="fa fa-pencil-alt"></i></a>
                                            </td>
                                        </tr>
                                        @php
                                            $no++
                                        @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <nav class="d-inline-block">
                                <ul class="pagination mb-0">
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1"><i
                                                class="fas fa-chevron-left"></i></a>
                                    </li>
                                    <li class="page-item active"><a class="page-link" href="#">1 <span
                                                class="sr-only">(current)</span></a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#">2</a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection