routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);
Auth::routes();


Route::get('/', 'Web\KrucukController@index')->name('index');
Route::get('/detail/{id}', 'Web\KrucukController@detail')->name('detail');
Route::get('/search', 'Web\KrucukController@search')->name('search');
Route::get('/category/{slug}', 'Web\KrucukController@category')->name('category');
Route::post('/rate', 'Web\KrucukController@rateMerchant')->name('rate');
Route::get('/login', 'Web\KrucukController@login')->name('login');
Route::get('/register', 'Web\KrucukController@register')->name('register');
Route::post('/register/create', 'Web\KrucukController@registerCreate');
Route::get('/login-merchant', 'Web\KrucukController@loginMerchant')->name('login-merchant');
Route::get('/register-merchant', 'Web\KrucukController@registerMerchant')->name('register-merchant');
Route::post('/register-merchant/create', 'Web\KrucukController@registerMerchantCreate')->name('register-merchant-create');

Route::prefix('merchant')
     ->namespace('Web')
     ->group(function(){
          Route::get('/setting','MerchantController@setting')->name('merchant-setting');
          Route::post('/setting-update','MerchantController@settingUpdate')->name('merchant-setting-update');
          Route::get('/operational','MerchantController@operational')->name('merchant-operational');
          Route::post('/operational-update','MerchantController@operationalUpdate')->name('merchant-operational-update');
          Route::get('/information','MerchantController@information')->name('merchant-information');
          Route::post('/information-update','MerchantController@informationUpdate')->name('merchant-information-update');
          Route::get('/gallery','MerchantController@gallery')->name('merchant-gallery');
          Route::post('/gallery-update','MerchantController@galleryUpdate')->name('merchant-gallery-update');
          Route::get('/gallery-delete/{id}','MerchantController@galleryDelete')->name('merchant-gallery-delete');
          Route::get('/menu','MerchantController@menu')->name('merchant-menu');
          Route::post('/menu-update','MerchantController@menuUpdate')->name('merchant-menu-update');
     });

Route::prefix('admin')
     ->namespace('Admin')
     ->group(function(){
          Route::get('/','Dashboard@index');
          Route::resource('category','CategoryController');
          Route::resource('admin','AdminController');
          Route::resource('user','UserController');
          Route::resource('merchant','MerchantController')->names([
               'update' => 'merchant.update',
          ]);
          Route::resource('banner','BannerController');
     });

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Banner extends Model
{   
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $fillable = [
        'title', 'image','status'
    ];
}

app/Http/Controllers/Admin/BannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Banner;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Storage;

class BannerController extends Controller
{
    public function index(){
        $data['banners'] = Banner::all();
        return view('pages.admin.banner.index',$data);
    }

    public function create()
    {   
        $form = 'create';
        return view('pages.admin.banner.form',['form'=>$form]);
    }

    public function store(Request $request)
    {   
        $data = $request->all();

        $file = $request->file('image');
        $name = 'image'.time();
        $extension = $file->getClientOriginalExtension();
        $newName = $name.'.'.$extension;
        $path = $request->file('image')->storeAs('public/banners',$newName);
        $data['image'] = $newName;

        Banner::create($data);
        return redirect()->route('banner.index');
        
    }

    public function edit($id)
    {
        $item = Banner::findOrFail($id);
        $form = 'edit';
        return view('pages.admin.banner.form',[
            'item' => $item,
            'form' => $form
        ]);
    }

    public function update(Request $request, $id)
    {   
        $data = $request->all();
        $item = Banner::findOrFail($id);

        if($request->hasFile('image')){
            $file = $request->file('image');
            $name = 'image'.time();
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
            $path = $request->file('image')->storeAs('public/banners',$newName);
            $data['image'] = $newName;
            Storage::delete('public/banner',$request->image_lama);
        }

        $item->update($data);
        return redirect()->route('banner.index');
    }

    public function destroy($id)
    {
        $item = Banner::findOrfail($id);
        $item->delete();

        return redirect()->route('banner.index');
    }
}

resources/views/pages/admin/banner/form.blade.php
@extends('layouts.admin')

@section('title','Kategori Form')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Banner Forms</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item">Category</div>
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                         <form action="{{($form=='create')?route('banner.store'):route('banner.update',$item->id)}}" method="POST" enctype="multipart/form-data">
                            @php
                                if($form =='edit'){
                                    echo method_field('PUT');
                                }
                            @endphp
                            @csrf
                        <div class="card-body">
                            <div class="form-group">
                                @if (isset($item) && $item->image)
                                    <img src="{{Storage::url('public/banners'.$item->image)}}" width="200px" alt="">
                                @endif
                                <br>
                                <label>Banner</label>
                                <input type="file" name="image" id="title" class="form-control">
                                <input type="hidden" name="image_lama" value="{{isset($item->image)?$item->image:''}}">
                                @error('image')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" name="title" id="title" class="form-control" value="{{isset($item->title)?$item->title:old('title')}}">
                                @error('title')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="d-block">Status</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="status" id="status1" value="1" {{isset($item->status)?($item->status == '1')?'checked="checked"':'':old('title')}}>
                                    <label class="form-check-label" for="status1">
                                        On
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="status" id="status2" value="0" {{isset($item->status)?($item->status == '0')?'checked="checked"':'':old('title')}}>
                                    <label class="form-check-label" for="status2">
                                        Off
                                    </label>
                                </div>
                                @error('status')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="card-footer text-right">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/pages/admin/banner/index.blade.php
@extends('layouts.admin')

@section('title','Kategori')

@section('content')
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Banner</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                <div class="breadcrumb-item">Banner</div>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-md-4">
                <a href="{{url('admin/banner/create')}}" class="btn btn-icon btn-lg btn-success"><i class="fas fa-plus"></i> Tambah Banner</a>
            </div>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Full Width</h4>
                            <div class="card-header-form">
                                <form>
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped table-md">
                                    <tbody>
                                        <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Title</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                        @php
                                            $no = 1;
                                        @endphp
                                        @foreach ($banners as $banner)
                                        <tr>
                                            <td>{{$no}}</td>
                                            <td><img src="{{Storage::url('public/banners/'.$banner->image)}}" alt="" width="120px"></td>
                                            <td>{{$banner->title}}</td>
                                            <td>
                                                @if ($banner->status == 1)
                                                    <div class="badge badge-success">Active</div>
                                                @else
                                                    <div class="badge badge-danger">Not Active</div>
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{route('banner.edit',$banner->id)}}" class="btn btn-info"><i class="fa fa-pencil-alt"></i></a>
                                                <form action="{{route('category.destroy',$banner->id)}}" method="post" class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are You Sure?')"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                        @php
                                            $no++
                                        @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <nav class="d-inline-block">
                                <ul class="pagination mb-0">
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1"><i
                                                class="fas fa-chevron-left"></i></a>
                                    </li>
                                    <li class="page-item active"><a class="page-link" href="#">1 <span
                                                class="sr-only">(current)</span></a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#">2</a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection